### ISSUE TITLE
Using a quest item in the objective tracker results in blizzard error dialogue to ignore or disable zUI

### ISSUE THREAD

**Issue by radhaz** [zstenger93/zUI#36]
**FURTHER TESTING REQUIRED ON MY PART** I apologize for an incomplete error report but I can't test it further until tomorrow so the write-up will have to suffice. If you prefer you can close this out and wait until I have more info for you and I'll submit a proper report.

While doing a quest that had a "quest object" that you used to throw an item at mobs I noted that every time I attempted to click the item in the objective tracker it would error out with a message similar to "Action being performed by zUI should be done through Blizzard UI" and had an option to "ignore" or "disable". 

Disable of course disables zUI and ignore just kept things as is, doing a /reload did not change the outcome as every time I interacted with the object it would still produce the error popup. The work around was just dragging the item from my bag to my hotbar and using it there.

I will test it further tomorrow once I find another quest with a quest item and provide screen caps of everything as well isolate all the other addons to ensure its a zUI issue because I'm not even certain it is a zUI issue at this point. Again I apologize for the half-assed issue report close/delete if you like or leave it open and I'll come back with further info for you.

**Comment by radhaz** [comment]
> Are you using my bag mod by any chance?

No, I am using adibags. Here's my complete list of addons https://imgur.com/a/dDrh0rC if it's any use to you. So before I used your addon I was using kaleil's tracker https://www.curseforge.com/wow/addons/kaliels-tracker which makes an additional extra action button for users to use quest items, I'm not sure if that was an aesthetic choice or their solution for the error popping up?

**Comment by zstenger93** [comment]
> > Are you using my bag mod by any chance?
> 
> No, I am using adibags. Here's my complete list of addons https://imgur.com/a/dDrh0rC if it's any use to you. So before I used your addon I was using kaleil's tracker https://www.curseforge.com/wow/addons/kaliels-tracker which makes an additional extra action button for users to use quest items, I'm not sure if that was an aesthetic choice or their solution for the error popping up?

Exactly you are right, that's why they do it.
The fun thing is that for the objective tracker, I'm not using anything since all I do is hide the art stuff mostly and collapse

Right now even if you don't use that option, the events are still registered for that part. Right now I am trying to figure out which one is the client crying about.

The reason this is causing this issue even for you, is that you get  usable items, let it be a quest item, something you can open -> gets into your bag -> events fired -> one or more of them is what they don't want you to use -> you get the error sometimes

Would be nice to have an actual error than what it throws. :)

**Comment by radhaz** [comment]
Again if there's anything I can do to help troubleshoot let me know. I can imagine the frustration of getting a generic error without any properly identifiable information.

**Comment by zstenger93** [comment]
I might have fixed it, but needs testing. Since yesterday I've got 0 taint error. Let's see

**Comment by radhaz** [comment]
> I might have fixed it, but needs testing. Since yesterday I've got 0 taint error. Let's see

I think you did, I've tested it out with several different quests and its working fine (for me) now
